# Generated by Django 4.2.5 on 2023-12-25 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolit', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_create',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='product',
            name='time_create',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Время создания'),
        ),
    ]
