# Generated by Django 4.2.5 on 2023-12-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolit', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Логин'),
        ),
    ]
