# Generated by Django 4.2.5 on 2023-12-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolit', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userInfo',
            field=models.TextField(max_length=1000, verbose_name='Обо мне'),
        ),
    ]
